app/users/views.py
from ..models import *
from flask import jsonify, request, url_for, g, redirect, render_template, flash, make_response, Blueprint
import simplejson as json
from oauth import OAuthSignIn
from flask_login import login_user, current_user
from flask import session as login_session
from utils import auth, flash_errors, parse_datetime, login_required
from apis.foursquare_api import venues, getGeocodeLocation
from forms import LoginForm, RegisterForm, RequestForm, SearchForm
from .. import profile_photo, csrf

ip = 0
searchform = SearchForm

mod = Blueprint('users', __name__, template_folder='templates')

@auth.error_handler
def unauthorized():
    return make_response(jsonify( { 'error': 'Unauthorized access' } ), 403)
    # return 403 instead of 401 to prevent browsers from displaying the default auth dialog

@mod.before_request
def before_request():
    g.user = current_user
    global ip
    ip = request.headers.getlist("X-Forwarded-For")[0] if request.headers.getlist("X-Forwarded-For") else request.remote_addr


@mod.route('/')
@mod.route('/index')
def index():
    if not login_session.get('username') :
        return redirect(url_for('users.login'))

    request_user = session.query(Request, DateTimeRequest). \
    filter(Request.user_id==login_session['id']). \
    filter(DateTimeRequest.request==Request.id).all()

    return render_template('index.html',
                      user_authenticated=True,
                      login_session=login_session,
                      request=RequestForm(request.form),
                      request_user=request_user,
                      searchform=searchform(request.form))


@mod.route('/login', methods=["GET", "POST"])
def login():
    if login_session.get('username'):
        return redirect(url_for('users.index'))
    form = LoginForm(request.form)
    if request.method == 'POST' and form.validate():
        username = form.username.data
        password = form.password.data
        registered_user = session.query(User). \
                          filter_by(username=username).first()
        if registered_user is None or not registered_user.verify_password(password):
            flash('Username or Password is invalid' , 'error')
            return redirect(url_for('users.login'))
        image = session.query(ProfileImage).filter_by(user_id=registered_user.id).first()
        login_user(registered_user) #flask login
        login_session['username'] = registered_user.username
        login_session['picture'] = '../'+str(image.image_url)
        login_session['email'] = registered_user.email
        login_session['id'] = registered_user.id
        flash('Logged in successfully')
        return redirect(request.args.get('next') or url_for('users.index'))

    return render_template('login.html',
                            user_authenticated=False,
                            formlogin=form,
                            formregister=RegisterForm(request.form),
                            searchform=searchform(request.form),
                            )

@mod.route('/register' , methods=['GET','POST'])
def register():
    form = RegisterForm(request.form)
    if request.method == 'POST':
        user = User(username=form.username.data, email=form.email.data)
        query_validate_username = session.query(User).filter_by(username=form.username.data).first()
        query_validate_email = session.query(User).filter_by(email=form.email.data).first()
        if query_validate_username is not None or query_validate_email is not None:
            uri_parameters = 'invalid'
            flash('That dates in use')
            return redirect(url_for('login', error=uri_parameters))
        user.hash_password(form.password.data)
        session.add(user)
        session.commit()
        print request.files
        if 'profile_photo' in request.files:
            filename = profile_photo.save(request.files['profile_photo'])
            newprofilephoto = ProfileImage(user_id=user.id,
                                           image_filename=filename,
                                           image_url='static/img/profile/'+filename)
            session.add(newprofilephoto)
            session.commit()
        flash('User successfully registered')
    else:
        flash_errors(form)
        return redirect(url_for('users.login'))

    return redirect(url_for('users.login'))


@mod.route('/logout', methods = ['GET'])
def logout():
    # this need refactor
    login_session.clear()
    return redirect(url_for('users.login'))


@mod.route('/oauth/<provider>')
def oauth_authorize(provider):
    oauth = OAuthSignIn.get_provider(provider)
    return oauth.authorize()


@mod.route('/callback/<provider>')
def oauth_callback(provider):
    oauth = OAuthSignIn.get_provider(provider)
    social_id, username, email, picture = oauth.callback()
    user = session.query(User).filter_by(email=email).first()
    if not user:
        user = User(username = username, picture = picture, email = email)
        session.add(user)
        membership = OAuthMembership(provider = provider, provider_userid = social_id, user = user)
        session.add(membership)
        session.commit()
    login_user(user)
    login_session['username'] = user.username
    login_session['picture'] = picture # wtf
    login_session['email'] = user.email
    login_session['id'] = user.id
    token = user.generate_auth_token(1600)

    return redirect(url_for('users.index', token = token))


@mod.route('/token')
@auth.login_required
def get_auth_token():
    token = g.user.generate_auth_token()
    return jsonify({'token': token.decode('ascii')})


@mod.route('/create_request', methods = ['GET', 'POST'])
def create_request():
    form = RequestForm(request.form)
    if request.method == 'POST' and form.validate():
        geolocation = getGeocodeLocation(form.location_string.data)
        newrequest = Request(user_id=login_session['id'],
                          meal_type=form.meal_type.data,
                          location_string=form.location_string.data,
                          latitude=geolocation[0],
                          longitude=geolocation[1])
        session.add(newrequest)
        session.commit()
        date_request = parse_datetime(year=form.year.data, month=form.month.data, day=form.day.data)
        if date_request == None:
            flash('Date no valid...')
            return redirect(url_for('users.index'))
        newrequestdate = DateTimeRequest(
                            request=newrequest.id,
                            mealtime=form.meal_time.data,
                            date=date_request)
        session.add(newrequestdate)
        session.commit()
        flash('Succefully!')
        return redirect(url_for('users.index'))
    flash_errors(form)
    return redirect(url_for('users.index'))

@mod.route('/request/delete/<int:id>', methods=['GET', 'POST'])
def delete_request(id):
    user = g.user
    r = session.query(Request).filter_by(id = id).first()
    d = session.query(DateTimeRequest).filter_by(request = r.id).first()
    session.delete(r)
    session.delete(d)
    session.commit()
    return redirect(url_for('users.index'))

@mod.route('/request/edit', methods=['POST'])
def request_edit():
    if request.method == "POST":
        data = json.loads(request.data)
        request_query = session.query(Request).filter_by(id = data['id']).first()
        request_query_datetime = session.query(DateTimeRequest).filter_by(request = request_query.id).first()

        geolocation = getGeocodeLocation(data['location'])

        new = [data['meal_type'], data['location'],
               geolocation[0], geolocation[1]]
        old = [request_query.meal_type, request_query.location_string,
               request_query.latitude, request_query.longitude]

        if set(new) != set(old):
            request_query.edit_meal_type = data['meal_type']
            request_query.edit_location_string = data['location']
            request_query.edit_latitude = geolocation[0]
            request_query.edit_longitude = geolocation[1]
            session.add(request_query)
            session.commit()

    return redirect(url_for('users.index'))

@mod.route('/request/edit/values', methods=['GET', 'POST'])
def values_form_edit_request():
        if request.method == "GET":
            request_id = request.args.get('id')
            print request_id
            r = session.query(Request).filter_by(id = request_id).first()
            #print r.serialize
            return json.dumps({'status':'OK',
                                'meal': r.serialize
                              })


@csrf.exempt
@mod.route('/search/', methods=['POST'])
def search():
    form = searchform(request.form)
    if form.validate():
        city = form.search.data
        venues_query = venues(city, mealtype='donuts', limit=5)
        return render_template('explorer.html',
                               query=venues_query,
                               searchform=searchform(request.form))


@mod.route('/request/all', methods=['GET'])
def all_request():
    form = searchform(request.form)
    requests = session.query(Request, DateTimeRequest). \
    filter(Request.filled==False).all()
    return render_template('all_request.html',
                           requests=requests,
                           searchform=searchform(request.form))


@mod.route('/proposal/create/<int:id>', methods=['GET'])
def create_proposal(id):
    r = session.query(Request).filter_by(id=id).first()
    if  r.user_id == login_session['id']:
        flash('Cannot create proposal for your request')
        return redirect(url_for('users.all_request'))
    p = Proposal(
        user_proposed_to=login_session['id'],
        user_proposed_from=r.user_id,
        request_id=r.id,
        filled=False
    )
    session.add(p)
    session.commit()
    flash('Succefully!')
    return redirect(url_for('users.index'))

app/templates/_ajax.get_request_edit.html
{% block ajaxget %}
<script>
        var csrftoken = $('meta[name=csrf-token]').attr('content')

        $.ajaxSetup({
            beforeSend: function(xhr, settings) {
                if (!/^(GET|HEAD|OPTIONS|TRACE)$/i.test(settings.type) && !this.crossDomain) {
                    xhr.setRequestHeader("X-CSRFToken", csrftoken)
                }
            }
        })

        $('.ajax_edit_request').click(function(){
          $.ajax({
                  type: "GET",
                  url: "/request/edit/values",
                  data: { id: $(this).attr('id-request') },
                  //contentType:"application/json",
                  dataType: "json"
          })
            .done(function(response) {
                console.log( "success", response.meal);
                $('.ajax_meal_type').val(response.meal.meal_type);
                $('.ajax_location').val(response.meal.location_string);
                $('.ajax_meal_time').val(response.meal.meal_time);
                $('.ajax_date').val(response.meal.date);
                $('#submit_edit_request').attr('request-id', response.meal.id);
            })
            .fail(function() {
                console.log( "error" );
            })
            .always(function() {
                console.log( "complete" );
            });
        });
    </script>
{% endblock %}

app/templates/_ajax.set_request_edit.html
{% block ajaxset %}
<script>
        var csrftoken = $('meta[name=csrf-token]').attr('content')

        $.ajaxSetup({
            beforeSend: function(xhr, settings) {
                if (!/^(GET|HEAD|OPTIONS|TRACE)$/i.test(settings.type) && !this.crossDomain) {
                    xhr.setRequestHeader("X-CSRFToken", csrftoken)
                }
            }
        })

        $('.form-edit').on('submit', function(){
          $.ajax({
                  type: "POST",
                  url: "/request/edit",
                  data: JSON.stringify({
                        id: $('.form-edit').attr('request-id'),
                        meal_type: $('.ajax_meal_type').val(),
                        location: $('.ajax_location').val(),
                        meal_time: $('.ajax_meal_time').val(),
                        meal_date: $('.meal_date').val()
                  }),
                  contentType: 'application/json;charset=UTF-8',
          })
         .done(function() {
             console.log( "done!" );
             window.location.replace("/index");

         })
         .fail(function() {
             console.log( "error" );
         })
         .always(function() {
            console.log( "complete" );
         });
        });
    </script>
{% endblock %}

app/templates/_macrovenues.html
{% macro rendervenues(venues) %}
      {% for r in venues %}
      <div>
              {% if r.picture %}
              <div class="    " style="background: url('{{r.picture }}') center / cover;">
              {% else %}
               <div class="    " style="background: url('{{ url_for('static', filename = 'img/fede.jpg') }}') center / cover;">
               {%endif%}

                  <h2 class="  ">{{ r.name }}</h2>
              </div>
              <div class="">
                  <h6>{{r.location}}</h6>
                  <hr>
                  {% if r.menu_url %}
                    <a href="{{r.menu_url}}" class="">
                    View Menu
                    </a>
                  {% endif %}
              </div>
              {% if r.menu_url %}
              <div class="">
                <a href="{{r.url}}" class="">
                  Visit web
                </a>
              </div>
               {% endif %}

              <div class="">
                <button class="">
                  <i class="material-icons">share</i>
                </button>
              </div>
            </div>
    {% endfor %}
{% endmacro %}

app/templates/all_request.html
{% extends 'base.html' %}
{% block content %}
<div ng-controller="requestview" class="indexbg">
  {% for n in requests %}
            <div class="">
              {{n[0].meal_type}}
              {{n[0].location_string}}
              {{n[1].mealtime}}
              {{n[1].date}}
              {{n[0].filled|string()}}
              <a href="{{url_for('users.create_proposal', id=n[0].id)}}">Create Proposal</a>
            </div>
  {% endfor %}
</div>
{% endblock %}

app/templates/base.html
<!doctype html>
<html>
<head>
    <title>Meet N' Eat</title>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="description" content="A front-end template that helps you build fast, modern mobile web apps.">
    <meta name="viewport" content="width=device-width, initial-scale=1.0, minimum-scale=1.0">
    <meta name="csrf-token" content="{{ csrf_token() }}">
    <link href="https://fonts.googleapis.com/icon?family=Material+Icons" rel="stylesheet">
    <script src="//ajax.googleapis.com/ajax/libs/angularjs/1.4.9/angular.min.js"></script>
    {% assets "js_angular" %}
    <script src="{{ ASSET_URL }}"></script>
    {% endassets %}
    {% assets "css_bootstrap" %}
    <link rel="stylesheet" href="{{ ASSET_URL }}" type="text/css" />
    {% endassets %}
    {% assets "js_bootstrap" %}
    <script src="{{ ASSET_URL }}"></script>
    {% endassets %}
</head>
<body ng-app="flask_app">
    <h1>Meet n' Eat</h1>
    {% if user_authenticated %}
        <h1>{{login_session.username}}</h1>
        <a href="{{ url_for('users.logout') }}" class="mdl-chip__action"><i class="material-icons">cancel</i></a>
    {% endif %}
    <form id="form_search_venues"  method="POST"  action="{{ url_for('users.search')}}">
        <div class="">
            <label class="" for="">
                <i class="material-icons">search things in a city</i>
            </label>
            <div class="">
                {{ searchform.search(class="mdl-textfield__input", type="search", id="site-search") }}
                <label class="" for="">Search</label>
            </div>
        </div>
    </form>


    {% for message in get_flashed_messages(with_categories=false) %}
      <div>
        <strong>{{ message }}!</strong>
      </div>
    {% endfor %}


    {% block content %}

    {% endblock %}
  <a href="http://flask.pocoo.org/" ><img
   src="http://flask.pocoo.org/static/badges/i-wish.png"
   border="0"
   alt="I wish this site were Flask powered"
   title="I wish this site were Flask powered">
  </a>
</body>
</html>

app/templates/createrequest.html
{% block request %}
<div class="" ng-show='request'>
    <h4>Request</h4>
    <form method="POST" action="{{ url_for('users.create_request') }}">
    <input type="hidden" name="csrf_token" value="{{ csrf_token() }}" />
        <div class="      ">
            {{request.meal_type(class_ ='')}}
            <label class="  ">{{request.meal_type.label}}</label>
        </div>
        <div class="        ">
            {{request.location_string(class_ ='')}}
            <label class="  ">{{request.location_string.label}}</label>
        </div>
        <div class=" ">
            {{request.meal_time}}
            {{request.year}}
            {{request.month}}
            {{request.day}}
        </div>
        <br>
        <div class="        ">
            {{request.submit(class_ ='mdl-button mdl-js-button mdl-button--raised mdl-js-ripple-effect')}}
        </div>
    </form>
</div>
{% endblock %}

app/templates/explorer.html
{% extends 'base.html' %}
{% from "_macrovenues.html" import rendervenues with context %}

{% block content %}
<div class="">
    {{ rendervenues(query) }}
</div>
{% endblock %}

app/templates/index.html
{% extends 'base.html' %}
{% block content %}
<div class="indexbg" ng-controller="requestview" class="indexbg">
    <div class="">
    <!-- Colored raised button -->
        <button class=""
         ng-click="action()">
         {a action_string a}
        </button>
        <button class=""
         ng-click="request_table()">
         {a request_table_string a}
        </button>
        <a class="" href="{{url_for('users.all_request')}}">All REQUEST</a>
        <a class="" href="{{url_for('users.my_proposal')}}">MY PROPOSALS</a>
        <a class="" href="{{url_for('users.my_mealdate')}}">MY MEALDATES</a>
        <img style="float:right;" src="{{login_session['picture']}}" width="100px" alt="userimg">
    </div>
    {% include  'createrequest.html' %}
    {% block request %}
    {% endblock%}
    <hr>
    <div ng-show="table">
    <h3>Me requests:</h3><hr>
    <div class="">
        <table class="mdl-data-table mdl-js-data-table">
        <thead>
            <tr>
            <th class="">Meal</th>
            <th class="">Location</th>
            <th>Meal Time</th>
            <th>Date</th>
            <th class="">Filled?</th>
            </tr>
        </thead>
        <tbody>
            {% for n in request_user %}
            <tr>
            <td class="">{{n[0].meal_type}}</td>
            <td>{{n[0].location_string}}</td>
            <td>{{n[1].mealtime}}</td>
            <td>{{n[1].date}}</td>
            <td>{{n[0].filled|string()}}</td>
            <td>
                <a href="{{url_for('users.delete_request', id=n[0].id)}}" class="">
                    <i class="material-icons">delete</i>
                </a>
            </td>
            <td>
                <button ng-click="request_edit()" id-request="{{n[0].id}}"  class="ajax_edit_request">
                    <i class="material-icons">edit</i>
                </button>
            </td>
            </tr>
            {% endfor %}
        </tbody>
        </table>
        </div>
    </div>
   <div class=""  ng-show="edit">
        <button class="" ng-click="cancel()">
                {a edit_string a}
        </button>
        <h4>Edit Request</h4>
        <form class="form-edit" id="submit_edit_request">
            <div class="    ">
                <input class="      ajax_meal_type" type="text"/>
            </div>
            <div class="   ">
                <input class="      ajax_location" type="text"/>
            </div>
            <div class="   ">
                <input class="      ajax_meal_time"  type="text"/>
            </div>
            <br>
            <input type="date" class="ajax_date meal_date" placeholder="yyyy-MM-dd"required />
            <br>
            <button type="submit" class="">
                    Edit!
            </button>
        </form>
        </div>
            {% include  '_ajax.get_request_edit.html' %}
            {% block ajaxget %}{% endblock%}
            {% include  '_ajax.set_request_edit.html' %}
            {% block ajaxset %}{% endblock%}
</div>
{% endblock %}

app/templates/login.html
{% extends 'base.html' %}
{% from "_macrovenues.html" import rendervenues with context %}

{% block content %}
<div class="inputbg" ng-controller="loginview" style="">
<div class="">
    <div class="">
            <a  class="" data-device="desktop" data-name="google" data-redirect="{{ url_for('users.index') }}" id='js-google-oauth-login' href="{{ url_for('users.oauth_authorize', provider='google') }}">Login with Google</a>
        <button class="" ng-click="action()">{a action_string a}</button>
    </div>
    {% include  'register.html' %}
    {% block register %}
    {% endblock%}
  <div class="" ng-show="login">
      <h1>Login with your account!</h1>
      <form method="POST" action="{{url_for('users.login')}}">
      <input type="hidden" name="csrf_token" value="{{ csrf_token() }}" />
      <!-- Textfield with Floating Label -->

        <div class="">
            {{formlogin.username(class_ ='mdl-textfield__input')}}
            <label class="">Username...</label>
        </div>
        <div class="">
            {{formlogin.password(class_ ='mdl-textfield__input')}}
            <label class="">Password...</label>
        </div>
        <div class="">
            {{formlogin.submit(class_ ='mdl-button mdl-js-button mdl-button--raised mdl-js-ripple-effect')}}
        </div>
      </form>
  </div>
</div>
</div>
{% endblock %}

app/templates/register.html
{% block register %}
  <div class="" ng-show="register">
      <h1>Register now!</h1>
      <form method="POST" enctype=multipart/form-data action="{{url_for('users.register')}}">
      <input type="hidden" name="csrf_token" value="{{ csrf_token() }}" />
        <div class="          ">
           {{formregister.username(class_ ='')}}
           <label class="   " for="sample3">{{formregister.username.label}}</label>
        </div>
        <div class="          ">
           {{formregister.password(class_ ='')}}
           <label class="   " for="sample3">{{formregister.password.label}}</label>
        </div>
        <div class="          ">
           {{formregister.confirm_password(class_ ='')}}
           <label class="   " for="sample3">{{formregister.confirm_password.label}}</label>
        </div>
        <div class="          ">
           {{formregister.email(class_ ='')}}
           <label class="  " for="sample3">{{formregister.email.label}}</label>
        </div>
        <div class="          ">
           {{formregister.confirm_email(class_ ='')}}
           <label class="  " for="sample3">{{formregister.confirm_email.label}}</label>
        </div>
           {{formregister.profile_photo}}
           <hr><br>
      <div>
        <button type="submit" name='submit' class="">
          Submit
        </button>
      </div>
      </form>
  </div>
{% endblock %}